"""Tests for state.py — the bot's persistent memory in a hidden PR comment.

The bot embeds JSON inside an HTML comment marker so it survives across
workflow runs without using ephemeral workflow artifacts.
"""
import json
import pytest
from ai_approve.state import (
    MARKER_START, MARKER_END,
    serialize_state, parse_state, embed_in_comment, extract_from_comment,
    empty_state,
)


def test_empty_state_has_expected_keys():
    s = empty_state(pr_number=42)
    assert s["pr"] == 42
    assert s["fix_attempts"] == []
    assert s["last_human_sha"] is None
    assert s["last_reviewed_sha"] is None
    assert s["total_bot_fixes"] == 0


def test_serialize_then_parse_roundtrips():
    s = empty_state(pr_number=42)
    s["total_bot_fixes"] = 3
    body = serialize_state(s)
    parsed = parse_state(body)
    assert parsed == s


def test_embed_and_extract_roundtrips():
    s = empty_state(pr_number=42)
    s["total_bot_fixes"] = 1
    raw = embed_in_comment(s)
    # Body must contain both markers and not break human-readable text.
    assert MARKER_START in raw
    assert MARKER_END in raw
    extracted = extract_from_comment(raw)
    assert extracted == s


def test_extract_from_comment_returns_none_when_no_marker():
    assert extract_from_comment("just a normal PR comment") is None


def test_extract_from_comment_handles_marker_with_surrounding_text():
    s = empty_state(pr_number=42)
    raw = "Hi humans!\n\n" + embed_in_comment(s) + "\n\n(generated by bot)"
    extracted = extract_from_comment(raw)
    assert extracted["pr"] == 42


def test_parse_state_rejects_bad_json():
    with pytest.raises(ValueError):
        parse_state("not json")
