"""Step 8 — Post the final review to GitHub via gh API.

POST /repos/{owner}/{repo}/pulls/{number}/reviews with event = APPROVE |
REQUEST_CHANGES | COMMENT, body = our structured markdown, and an inline
comment per surviving comment.
"""
from __future__ import annotations

import json
import os
import subprocess


def render_body(
    *,
    verdict: str,
    pass2: dict,
    auto_fix_result: dict | None,
    dropped_comments: list[dict],
    critique_concerns: list[str],
    hard_block_reasons: list[str],
    rate_limit_remaining: int | None,
) -> str:
    confidence = pass2.get("confidence", "?")
    certainty = pass2.get("certainty", "?")
    summary = pass2.get("summary", "(no summary)")
    icon = {"APPROVE": "✅", "REQUEST_CHANGES": "❌", "COMMENT": "💬"}.get(verdict, "•")
    kept = pass2.get("comments", [])

    lines = [
        "## AI Review — Al-Malakia",
        "",
        f"**Verdict:** {icon} {verdict} "
        f"(confidence {confidence}, certainty {certainty})",
        f"**Tool calls used:** {pass2.get('tool_calls_used', 0)}/10  "
        f"**Tokens:** in={pass2.get('tokens_in_total', 0)} out={pass2.get('tokens_out_total', 0)}",
    ]
    if rate_limit_remaining is not None:
        lines.append(f"**Quota remaining (gpt-4o):** {rate_limit_remaining}")
    lines.append("")
    if hard_block_reasons:
        lines.append("### Hard-blocked")
        for r in hard_block_reasons:
            lines.append(f"- {r}")
        lines.append("")
    lines.append("### Summary")
    lines.append(summary)
    lines.append("")

    if auto_fix_result and auto_fix_result.get("acted"):
        lines.append(f"### Auto-fixes applied ({auto_fix_result['files_changed']} files)")
        for t in auto_fix_result.get("tools_used", []):
            lines.append(f"- `{t}`")
        lines.append("")
    elif auto_fix_result and auto_fix_result.get("stop_reason"):
        lines.append("### Auto-fix")
        lines.append(f"- _Skipped_: {auto_fix_result['stop_reason']}")
        lines.append("")

    if critique_concerns:
        lines.append("### Self-critique concerns (verdict downgraded)")
        for c in critique_concerns:
            lines.append(f"- {c}")
        lines.append("")

    if dropped_comments:
        lines.append("### Verification trail")
        lines.append(f"- {len(kept)} comments verified, {len(dropped_comments)} dropped by verifier (see workflow run summary)")
        lines.append("")

    lines.append("---")
    lines.append("🤖 Generated by `.github/workflows/ai-approve.yml`")
    return "\n".join(lines)


APPROVE_FALLBACK_NOTE = (
    "\n\n---\n"
    "**⚠️ Note on verdict:** The bot wanted to post `APPROVE` but the "
    "review API returned HTTP 422. Two known causes:\n\n"
    "1. **`GITHUB_TOKEN` cannot post APPROVE reviews** — documented "
    "GitHub limitation. Fix: set a `PR_REVIEW_TOKEN` repo secret "
    "(fine-grained PAT, `Pull requests: write`).\n\n"
    "2. **A user-account PAT cannot APPROVE the same user's own PR** "
    "— GitHub blocks self-approval. Fix: graduate to a dedicated "
    "GitHub App with `pull_requests:write` installed on the repo, OR "
    "ask another collaborator to approve.\n\n"
    "Posted as `COMMENT` instead so the review isn't lost. Auto-merge "
    "won't fire until `reviewDecision == APPROVED`."
)


def _post_one_attempt(
    *, repo: str, pr_number: int, review_payload: dict, token: str,
) -> tuple[int, str, str]:
    """Run gh api with the given token; return (returncode, stdout, stderr)."""
    cmd = [
        "gh", "api",
        f"repos/{repo}/pulls/{pr_number}/reviews",
        "--method", "POST",
        "--input", "-",
    ]
    r = subprocess.run(
        cmd, input=json.dumps(review_payload), text=True, capture_output=True,
        env={"GH_TOKEN": token, "PATH": os.environ.get("PATH", "")},
    )
    return r.returncode, r.stdout or "", r.stderr or ""


def post_review(
    *,
    repo: str,
    pr_number: int,
    head_sha: str,
    verdict: str,
    body: str,
    inline_comments: list[dict],
    token: str,
    review_token: str | None = None,
) -> dict:
    """POST the review. Returns the GitHub API response dict.

    `inline_comments` items: {file, line, body}

    Token strategy:
      - If `review_token` is provided (typically from a PR_REVIEW_TOKEN
        PAT secret), use it for the API call. This is what unlocks real
        `APPROVE` posting — GITHUB_TOKEN cannot do that.
      - Otherwise use `token` (GITHUB_TOKEN). For verdict=APPROVE this
        will return HTTP 422; we automatically fall back to posting as
        COMMENT with an explanatory note appended.
    """
    review = {
        "commit_id": head_sha,
        "body": body,
        "event": verdict,  # APPROVE | REQUEST_CHANGES | COMMENT
        "comments": [
            {"path": c["file"], "line": c["line"], "body": c["body"]}
            for c in inline_comments
        ],
    }

    use_token = review_token or token
    code, out, err = _post_one_attempt(
        repo=repo, pr_number=pr_number, review_payload=review, token=use_token,
    )
    if code == 0:
        return json.loads(out or "{}")

    # Any 422 on an APPROVE attempt is a known-shape failure (either
    # GITHUB_TOKEN can't approve, OR a user-PAT cannot approve their own
    # PR). Fall back to COMMENT regardless of which token was used so the
    # review isn't lost. The note explains both cases + the GitHub App
    # path so the user knows how to unlock real APPROVE later.
    looks_like_approve_block = (
        verdict == "APPROVE"
        and ("422" in err or "Unprocessable" in err)
    )
    if looks_like_approve_block:
        fallback = dict(review)
        fallback["event"] = "COMMENT"
        fallback["body"] = body + APPROVE_FALLBACK_NOTE
        code2, out2, err2 = _post_one_attempt(
            repo=repo, pr_number=pr_number, review_payload=fallback, token=use_token,
        )
        if code2 == 0:
            result = json.loads(out2 or "{}")
            result["_fallback_from_approve"] = True
            return result
        raise RuntimeError(
            f"post_review APPROVE→COMMENT fallback also failed: {err2}"
        )

    raise RuntimeError(f"post_review failed: {err}")


def inline_body_for_comment(c: dict) -> str:
    """Per-comment inline body. Includes severity tag + claim text."""
    sev = c.get("severity", "warn")
    prefix = {"info": "ℹ️", "nit": "nit:", "warn": "warn:", "major": "**major:**", "blocker": "🚫 **blocker:**"}.get(sev, "")
    out = f"{prefix} {c['claim']}"
    if c.get("suggested_text"):
        out += f"\n\n```suggestion\n{c['suggested_text']}\n```"
    return out
